import assert from 'node:assert/strict';
import { CollectionGallery } from '../dist/gallery.js';
import { modules } from '../dist/catalog.js';
globalThis.cancelAnimationFrame=()=>{};
globalThis.requestAnimationFrame=()=>1;
const child=()=>({style:{},classList:{toggle(){}},setAttribute(){}});
globalThis.matchMedia=()=>({matches:false,addEventListener(){}});
globalThis.ResizeObserver=class{observe(){}};
const stub=()=>({replaceChildren(){},append(){},addEventListener(){}});
globalThis.document={createElement:()=>({...stub(),setAttribute(){}})};
class GalleryHarness extends CollectionGallery { render(){} }
const g=new GalleryHarness({stage:stub(),nav:stub(),dots:stub(),previous:stub(),next:stub(),onSelect(){},onOpen(){}});
Object.assign(g,{items:modules,index:1,position:1,target:1,velocity:0,frame:0,lastTime:0,layout:'rail',motion:{matches:false},animations:[],stage:{clientWidth:1000,clientHeight:420,children:modules.map(child),style:{setProperty(){}},classList:{add(){},remove(){}},setPointerCapture(){},hasPointerCapture(){return false;}},dots:{children:[]},nav:{children:[]},previous:{},next:{},onSelect(){},onDraw(){}});
g.draw();
g.select(3);
assert.equal(g.index,1,'Selecting a destination must not switch the active scene before it arrives');
assert.equal(g.settled,false);
g.position=1.6;g.draw();assert.equal(g.index,2,'Current scene follows visible position before release');
g.position=1.2;g.draw();assert.equal(g.index,1,'Reversing a drag restores the nearest scene');
g.select(0);assert.equal(g.index,1,'Retargeting in flight must not jump state');
for(let t=0;t<2500;t+=16)g.tick(t);
assert.equal(g.index,0);assert.equal(g.position,0);assert.equal(g.settled,true);
g.select(3,true);assert.equal(g.index,3);assert.equal(g.position,3);
g.position=1;g.index=1;g.target=1;g.draw();
g.pointerDown({button:0,pointerType:'touch',target:{closest:()=>null},pointerId:1,clientX:700,clientY:500});
g.pointerMove({pointerId:1,clientX:350,clientY:500});
assert.equal(g.index,2,'Live pointer movement commits the visually nearest object');
assert.equal(g.settled,false,'Physical object manipulation is disabled during rail drag');
g.pointerEnd({pointerId:1},true);
for(let t=0;t<2500;t+=16)g.tick(t);
assert.equal(g.position,2);assert.equal(g.index,2);assert.equal(g.settled,true);
console.log('PASS: live drag selection, reversal, in-flight retarget, settling and immediate navigation');
